channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.0
  - psutil==5.9.0
  - scikit-learn==1.5.2
  - scipy==1.16.0
name: mlflow-env
