name: CI/CD MLflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  CSV_URL: "MLproject/train.csv"
  TARGET_VAR: "HeartDisease"

jobs:
  build:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          # Pastikan path ini sesuai dengan lokasi script preprocessing kamu
          mlflow run MLproject --env-manager=local 

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      - name: Set up Git LFS
        run: |
          git config --global user.name valiarw
          git config --global user.email valiarw1300@gmail.com
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
          
       # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name valiarw
          git config --global user.email valiarw1300@gmail.com
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
