name: CI/CD MLflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  CSV_URL: "train.csv"

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: USERNAME
          password: PASS_DOCKER

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag cc USERNAME/cc:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push USERNAME/cc:latest

